## NP Arrays class deeplearning.ai

In [2]:
import numpy as np

In [ ]:
# Creating Numpy arrays using list of values

one_dimensional_arr = np.array([10, 12])
one_dimensional_arr

array([10, 12])

In [6]:
# Creating Numpy arrays using list of values

a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
# Creating numpy arrays using arange

b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [8]:
# Creating numpy arrays using arange

c = np.arange(1, 20, 3)
c

array([ 1,  4,  7, 10, 13, 16, 19])

In [14]:
# Creating numpy arrays using arange

d = np.arange(0, 100, 5)
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [17]:
# Creating numpy arrays using linspace

e = np.linspace(0, 100, 5)
e


array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# change the type of values to int

lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
lin_spaced_arr_int

array([  0,  25,  50,  75, 100])

In [ ]:
# see the data type of the array

char_arr = np.array(['Welcome to Math for ML!'])

print(char_arr.dtype)
print(char_arr)

<U23
['Welcome to Math for ML!']


In [26]:
# creating more arrays

ones = np.ones(3)
zeros = np.zeros(3)
empt = np.empty(3)
rand = np.random.rand(3)

print(ones)
print(zeros)
print(empt)
print(rand)

[1. 1. 1.]
[0. 0. 0.]
[0. 0. 0.]
[0.16754135 0.30239118 0.29358417]


## multidimensional arrays

In [27]:
# creating a 2 dimensional array (2-d)

two_dim_arr = np.array([[1,2,3], [4,5,6]])
two_dim_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# creating 2 dimensional array using reshape

one_dim_arr = np.array([1,2,3,4,5,6])

multi_dim_arr = np.reshape(one_dim_arr, (2,3))

multi_dim_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# finding size, shape and dimension


print(multi_dim_arr.ndim)
print(multi_dim_arr.shape)
print(multi_dim_arr.size)

2
(2, 3)
6


## Array math operations

In [31]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

addition = arr_1 + arr_2
substraction = arr_1 - arr_2
multiplication = arr_1 * arr_2

print(addition)
print(substraction)
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [32]:
# multiplying vector with a scalar (broadcasting)


vector = np.array([1,2])

vector * 1.6


array([1.6, 3.2])

In [33]:
# indexing


a = ([1,2,3,4,5])

print(a[2])

print(a[0])


3
1


In [34]:
# indexing on a 2d array

two_dim = np.array(([1,2,3],
                    [4,5,6],
                    [7,8,9]))

print(two_dim[2][1])

8


In [37]:
# slicing

sliced_arr_1 = a[1:4]
sliced_arr_2 = a[:3]
sliced_arr_3 = a[2:]
sliced_arr_4 = a[::2]

print(sliced_arr_1)
print(sliced_arr_2)
print(sliced_arr_3)
print(sliced_arr_4)

[2, 3, 4]
[1, 2, 3]
[3, 4, 5]
[1, 3, 5]


In [38]:
# slicing

a == a[:] == a[::]

True

In [39]:
# slicing
sliced_1 = two_dim[0:2]
sliced_2 = two_dim[1:3]
sliced_columns = two_dim[:, 1]

print(sliced_1)
print(sliced_2)
print(sliced_columns)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[2 5 8]


## Stacking

In [40]:
# join two or more arrays, either horizontally or vertically

a1 = np.array([[1,1],
              [2,2]])

a2 = np.array([[3,3],
               [4,4]])

print(a1)

print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [41]:
# stack vertically

vert_stack = np.vstack((a1, a2))
vert_stack

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [42]:
horz_stack = np.hstack((a1, a2))
horz_stack

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## exercises

In [ ]:
# Q1: Is there a difference between np.zeros() and np.empty()? Select one of the options given:

#A. No difference, they both output arrays of zeros.
#B. np.zeros() is not initialized, but gives an output of zeros.
#C. np.zeros() is faster to execute than np.empty().
#D. np.empty() outputs an uninitialized array, but np.zeros() outputs an initialized array of value zero.

# Awnser =  D