## Introduction to the numpy.linalg sub-libary

In [1]:
import numpy as np

In [3]:
A = np.array([[4,-3,1],
              [2, 1, 3],
              [-1,2,-5]])

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print(f'Matrix: ', A)
print('-----------')
print(b)

Matrix:  [[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]]
-----------
[-10.   0.  17.]


In [4]:
np.shape(A)

(3, 3)

In [ ]:
# solving the system

x = np.linalg.solve(A, b)
x

array([ 1.,  4., -2.])

In [ ]:
# determinant

d = np.linalg.det(A)
d

-60.000000000000036

In [7]:
# if the system has no solution

A_2 = np.array([[1,1,1],
          [0, 1,-3,],
          [2,1,5]])

b_2 = np.array([2,1,0])

print(A_2)
print(b_2)

[[ 1  1  1]
 [ 0  1 -3]
 [ 2  1  5]]
[2 1 0]


In [8]:
print(np.linalg.solve(A_2, b_2))

LinAlgError: Singular matrix

In [9]:
d_2 = np.linalg.det(A_2)

print(d_2)

0.0
